<?php

namespace Slov\Expression\Operation;



use Slov\Expression\Code\CodeContext;

/** Операция сравнения */
abstract class CompareOperation extends Operation
{
    public function resolveReturnTypeName()
    {
        if(
            (
                $this->getLeftOperandTypeName()->isDigit()
                &&
                $this->getRightOperandTypeName()->isDigit()
            )
            ||
            (
                $this->getLeftOperandTypeName()->isDateTime()
                &&
                $this->getRightOperandTypeName()->isDateTime()
            )
            ||
            (
                $this->getLeftOperandTypeName()->isMoney()
                &&
                $this->getRightOperandTypeName()->isMoney()
            )
            ||
            (
                $this->getLeftOperandTypeName()->isDateInterval()
                &&
                $this->getRightOperandTypeName()->isDateInterval()
            )
        ){
            return $this->getTypeNameFactory()->createBoolean();
        }
        return $this->typeDefinitionFailed();
    }

    public function toPhp(CodeContext $codeContext): string
    {
        return parent::toPhp($codeContext); // TODO: Change the autogenerated stub
    }
}